apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: basic-app
  template:
    metadata:
      labels:
        app: basic-app
    spec:
      containers:
        - name: basic-app-container
          image: tejasivedha/basic_app:latest
          ports:
            - containerPort: 5000
